server:
  port: 8989

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/sparkx
    username: sparkx
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0 # 支持文件写入磁盘
      max-file-size: 50MB # 最大文件上传大小
      max-request-size: 100MB  # 最大支持请求大小
  mvc:
    async:
      request-timeout: 80000 # sse超时关闭报错问题
  web:
    resources:
      static-locations: classpath:/static/, file:${upload.upload-path}
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
upload:
  upload-path: ./upload
